USE MECHANIC_SHOP;

-- D List all the clients that have invoices for a car between 16 June and 21 April of 2023 --
SELECT DISTINCT CLIENT.CLIENT_ID, C_NAME
FROM CLIENT
JOIN CAR
ON CAR.CLIENT_ID = CLIENT.CLIENT_ID
JOIN INVOICE
ON INVOICE.CAR_ID = CAR.CAR_ID
WHERE INVOICE.I_DATE BETWEEN '2023-04-21' AND '2023-06-16';

-- E Provide a list of Client names and emails for all the Clients that have an invoice with a part call “super turbo” on it --
SELECT DISTINCT C_NAME, C_EMAIL
FROM CLIENT
JOIN CAR
ON CAR.CLIENT_ID = CLIENT.CLIENT_ID
JOIN INVOICE
ON INVOICE.CAR_ID = CAR.CAR_ID
JOIN PART
ON PART.I_ID = INVOICE.I_NO
WHERE PART.P_NAME = 'super turbo';

-- F List the number of parts each client has paid for --
SELECT CLIENT.CLIENT_ID, SUM(INVOICE.QUANTITY)
FROM CLIENT
JOIN CAR
ON CAR.CLIENT_ID = CLIENT.CLIENT_ID
JOIN INVOICE
ON INVOICE.CAR_ID = CAR.CAR_ID
WHERE INVOICE.I_PAYMENT_STATUS = '0'
GROUP BY CLIENT.CLIENT_ID;

-- G What is the average value of “Unpaid” invoices? --
SELECT AVG(PART.P_PRICE)
FROM CLIENT
JOIN CAR
ON CAR.CLIENT_ID = CLIENT.CLIENT_ID
JOIN INVOICE
ON INVOICE.CAR_ID = CAR.CAR_ID
JOIN PART
ON PART.I_ID = INVOICE.I_NO
WHERE INVOICE.I_PAYMENT_STATUS = '0';

-- H Which client owns the mechanic shop the most money? --
SELECT DISTINCT TOP 1 CLIENT.CLIENT_ID, CLIENT.C_NAME, CLIENT.C_SURNAME, SUM(PART.P_PRICE)
FROM CLIENT
JOIN CAR
ON CAR.CLIENT_ID = CLIENT.CLIENT_ID
JOIN INVOICE
ON INVOICE.CAR_ID = CAR.CAR_ID
JOIN PART
ON PART.I_ID = INVOICE.I_NO
WHERE INVOICE.I_PAYMENT_STATUS = '0'
GROUP BY CLIENT.CLIENT_ID, CLIENT.C_NAME, CLIENT.C_SURNAME
ORDER BY SUM(PART.P_PRICE) DESC;